services:
  redis:
    image: 'redis:alpine'
    # ports:
    #   - '6379:6379'
    command: "redis-server --save 60 1 --loglevel warning"
    networks:
      - app-net
  app-worker-bee:
    build:
      context: ./app-worker-bee
    container_name: app-worker-bee
    expose:
      - 3000
    networks:
      - app-net
    depends_on:
      - redis
  worker-nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
