version: '3.8'

services:
  redis:
    image: 'redis:alpine'
    # ports:
    #   - '6379:6379'
    command: "redis-server --save 60 1 --loglevel warning"
    networks:
      - app-net
  app-worker-bee:
    build: .
    container_name: app-worker-bee
    expose:
      - 3000
    networks:
      - app-net
    depends_on:
      - redis

networks:
  app-net:
    external: true
    name: worker-network
