version: '3.8'

services:
  app-worker-bee:
    build: .
    container_name: app-worker-bee
    expose:
      - 3000
    networks:
      - app-net

networks:
  app-net:
    external: true
    name: worker-network
